### ISSUE TITLE
Match people based on activity score. 

### ISSUE THREAD

**Issue by johan-t** [Contraversum/ContraBot#69]
There is a problem with users getting matched and not being active we could match people based on their activity

**Comment by TheLlamamarketer** [comment]
Very out there idea I'm throwing out from someone else: could we not add an activity button that can be pushed by the user to influence the activity score? That button could be prompted to be pushed by the user, if lets say their activity score drops too low. 

Maybe even we can tell the user if they are inactive, as it could be that the user is not active on the server because they are not getting matches, after only having  been matched with one other user?

**Comment by johan-t** [comment]
What I was thinking is maybe we should see if one of the users has not written a message in the chat. If they have not written anything after say 3 days the inactive user is deleted from the db and the active user gets a new match. What do you think about this?
